# Generated by Django 6.0.3 on 2026-04-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_name', models.CharField(max_length=10)),
                ('M_name', models.CharField(max_length=10)),
                ('L_name', models.CharField(max_length=10)),
                ('Martial_status', models.CharField()),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.CharField(verbose_name=10)),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
    ]
